### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by philipk19238** [square/square-python-sdk#105] opened 2023-02-04 10:58 UTC
**Describe the bug**

I've been experiencing consistent timeouts with the Square API. I have verified the credentials I have been using is correct - including access token, application ID, etc. I also recreated the requests using cURL and the requests library and those requests are timing out as well. (I made sure to ping some other public endpoints as well to ensure it wasn't a network issue on my end)

Here are the logs I get:

```bash
File "/backend/./www/www/api/auth_controller.py", line 39, in end_square_oauth_flow
sweetspot-backend-1  |     oauth_client = auth.get_square_client(oauth_end_flow.access_token)
sweetspot-backend-1  |   File "/backend/./common/common/square/auth.py", line 48, in get_square_client
sweetspot-backend-1  |     return Client(access_token, settings.SQUARE_ENVIRONMENT)
sweetspot-backend-1  |   File "/usr/local/lib/python3.8/site-packages/square/client.py", line 228, in __init__
sweetspot-backend-1  |     self.config = Configuration(
sweetspot-backend-1  |   File "/usr/local/lib/python3.8/site-packages/square/configuration.py", line 68, in __init__
sweetspot-backend-1  |     super().set_http_client(self.create_http_client())
sweetspot-backend-1  |   File "/usr/local/lib/python3.8/site-packages/square/configuration.py", line 103, in create_http_client
sweetspot-backend-1  |     return RequestsClient(
sweetspot-backend-1  |   File "/usr/local/lib/python3.8/site-packages/apimatic_requests_client_adapter/requests_client.py", line 45, in __init__
sweetspot-backend-1  |     http_client_instance.timeout = timeout
```

**Expected behavior**
I expect the API call to immediately return me a response.

**To Reproduce**
Steps to reproduce the bug:
1. Initiate API Client
2. Pass in Access Token
3. Make request

**Screenshots**
If applicable, add screenshots to help explain the bug.

**Square SDK version**
squareup==25.0.0.20221214

**Additional context**
Run inside local docker container (Fast API)

**Comment by havenwood** [comment] 2023-03-27 18:35
Since this can be reproduced from cURL it seems the issue isn't specific to the SDK and is instead related to some combination of the server environment, network and Square API.

@philipk19238 I'm just closing this issue here since it doesn't appear to be caused by the SDK itself, but if you're having any ongoing issues please join us in https://squ.re/slack or https://developer.squareup.com/forums and we can help debug what's going on with the failed requests.

**Closed by havenwood** 2023-03-27 18:35 UTC
